
src=<<__eos__



__eos__

words = {
  "TINTOK_NEW_LINE" => "TINTOK_NEWLINE",
  "TINTOK_LEFT_PAREN" => "TINTOK_PARENOPEN",
  "TINTOK_RIGHT_PAREN" => "TINTOK_PARENCLOSE",
  "TINTOK_LEFT_BRACE" => "TINTOK_BRACEOPEN",
  "TINTOK_RIGHT_BRACE" => "TINTOK_BRACECLOSE",
  "TINTOK_LEFT_BRACKET" => "TINTOK_BRACKETOPEN",
  "TINTOK_RIGHT_BRACKET" => "TINTOK_BRACKETCLOSE",
  "TINTOK_COMMA" => "TINTOK_COMMA",
  "TINTOK_SEMICOLON" => "TINTOK_SEMICOLON",
  "TINTOK_COLON" => "TINTOK_COLON",
  "TINTOK_BAR_EQUAL" => "TINTOK_ASSIGNEQUAL",
  "TINTOK_BAR" => "TINTOK_BAR",
  "TINTOK_BAR_BAR" => "TINTOK_DOUBLEBAR",
  "TINTOK_AMPERSAND_EQUAL" => "TINTOK_AMPERSANDEQUAL",
  "TINTOK_AMPERSAND" => "TINTOK_AMPERSAND",
  "TINTOK_AMPERSAND_AMPERSAND" => "TINTOK_DOUBLEAMPERSAND",
  "TINTOK_BANG" => "TINTOK_BANG",
  "TINTOK_BANG_EQUAL" => "TINTOK_BANGEQUAL",
  "TINTOK_EQUAL" => "TINTOK_ASSIGN",
  "TINTOK_EQUAL_EQUAL" => "TINTOK_EQUAL",
  "TINTOK_GREATER" => "TINTOK_GREATERTHAN",
  "TINTOK_GREATER_EQUAL" => "TINTOK_GREATEREQUAL",
  "TINTOK_GREATER_GREATER" => "TINTOK_SHIFTRIGHT",
  "TINTOK_LESS" => "TINTOK_LESSTHAN",
  "TINTOK_LESS_EQUAL" => "TINTOK_LESSEQUAL",
  "TINTOK_LESS_LESS" => "TINTOK_SHIFTLEFT",
  "TINTOK_PLUS" => "TINTOK_PLUS",
  "TINTOK_PLUS_EQUAL" => "TINTOK_PLUSEQUAL",
  "TINTOK_PLUS_PLUS" => "TINTOK_DOUBLEPLUS",
  "TINTOK_MINUS" => "TINTOK_MINUS",
  "TINTOK_MINUS_EQUAL" => "TINTOK_MINUSEQUAL",
  "TINTOK_MINUS_MINUS" => "TINTOK_DOUBLEMINUS",
  "TINTOK_STAR" => "TINTOK_STAR",
  "TINTOK_STAR_EQUAL" => "TINTOK_STAREQUAL",
  "TINTOK_STAR_STAR" => "TINTOK_DOUBLESTAR",
  "TINTOK_SLASH" => "TINTOK_SLASH",
  "TINTOK_SLASH_EQUAL" => "TINTOK_SLASHEQUAL",
  "TINTOK_QUESTION" => "TINTOK_QUESTION",
  "TINTOK_QUESTION_QUESTION" => "TINTOK_DOUBLEQUESTION",
  "TINTOK_PERCENT" => "TINTOK_PERCENT",
  "TINTOK_PERCENT_EQUAL" => "TINTOK_PERCENTEQUAL",
  "TINTOK_ARROW" => "TINTOK_ARROW",
  "TINTOK_SMALL_ARROW" => "TINTOK_SMALLARROW",
  "TINTOK_TILDE" => "TINTOK_TILDE",
  "TINTOK_CARET" => "TINTOK_CARET",
  "TINTOK_CARET_EQUAL" => "TINTOK_CARETEQUAL",
  "TINTOK_DOT" => "TINTOK_DOT",
  "TINTOK_DOT_DOT" => "TINTOK_DOUBLEDOT",
  "TINTOK_DOT_DOT_DOT" => "TINTOK_TRIPLEDOT",
  "TINTOK_SHARP" => "TINTOK_SHARP",
  "TINTOK_SHARP_EQUAL" => "TINTOK_SHARPEQUAL",
  "TINTOK_IDENTIFIER" => "TINTOK_IDENT",
  "TINTOK_STRING" => "TINTOK_STRING",
  "TINTOK_INTERPOLATION" => "TINTOK_STRINTERPOL",
  "TINTOK_NUMBER" => "TINTOK_NUMBER",
  "TINTOK_CLASS" => "TINTOK_KWCLASS",
  "TINTOK_ELSE" => "TINTOK_KWELSE",
  "TINTOK_FALSE" => "TINTOK_KWFALSE",
  "TINTOK_FOR" => "TINTOK_KWFOR",
  "TINTOK_FUNCTION" => "TINTOK_KWFUNCTION",
  "TINTOK_IF" => "TINTOK_KWIF",
  "TINTOK_NULL" => "TINTOK_KWNULL",
  "TINTOK_RETURN" => "TINTOK_KWRETURN",
  "TINTOK_SUPER" => "TINTOK_KWSUPER",
  "TINTOK_THIS" => "TINTOK_KWTHIS",
  "TINTOK_TRUE" => "TINTOK_KWTRUE",
  "TINTOK_VAR" => "TINTOK_KWVAR",
  "TINTOK_WHILE" => "TINTOK_KWWHILE",
  "TINTOK_CONTINUE" => "TINTOK_KWCONTINUE",
  "TINTOK_BREAK" => "TINTOK_KWBREAK",
  "TINTOK_NEW" => "TINTOK_KWNEW",
  "TINTOK_EXPORT" => "TINTOK_KWEXPORT",
  "TINTOK_IS" => "TINTOK_KWIS",
  "TINTOK_STATIC" => "TINTOK_KWSTATIC",
  "TINTOK_OPERATOR" => "TINTOK_KWOPERATOR",
  "TINTOK_GET" => "TINTOK_KWGET",
  "TINTOK_SET" => "TINTOK_KWSET",
  "TINTOK_IN" => "TINTOK_KWIN",
  "TINTOK_CONST" => "TINTOK_KWCONST",
  "TINTOK_REF" => "TINTOK_KWREF",
  "TINTOK_ERROR" => "TINTOK_ERROR",
  "TINTOK_EOF" => "TINTOK_EOF",

}

cmd = ["gsub", "-g", "*.{h,c}", "-b", "-r"]
#src.split(",").map(&:strip).reject(&:empty?).each do |n|
words.each do |n, nn|
  #nb = n.split(/_/)
  #first = nb.shift
  #rest = nb.join
  #nn = first + "_" + rest
  printf("  %p => %p,\n", n, nn)
  cmd.push(sprintf("%s=%s", n, nn))
end

system(*cmd)

